pub type Position = (usize, usize);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenType {
    Let,
    Const,
    Fn,
    Class,
    New,
    This,
    Super,
    Constructor,
    Return,
    If,
    In,
    Else,
    While,
    For,
    Break,
    Continue,
    Interface,
    Enum,
    TypeAlias,
    Typeof,
    KeyOf,
    Instanceof,
    Readonly,
    Implements,
    Extends,
    Static,
    Private,
    Public,
    Protected,
    Async,
    Await,
    Try,
    Catch,
    Finally,
    Throw,
    Get,
    Set,
    Import,
    Export,
    From,
    As,
    Default,
    Declare,
    At,
    Identifier,
    IntLiteral,
    FloatLiteral,
    StrLiteral,
    True,
    False,
    NullLiteral,
    Plus,
    Minus,
    Multiply,
    Divide,
    Modulo,
    Assign,
    PlusAssign,
    MinusAssign,
    MultiplyAssign,
    DivideAssign,
    ModuloAssign,
    Eq,
    Neq,
    Lt,
    Gt,
    Lte,
    Gte,
    And,
    Or,
    Not,
    Dot,
    Range,
    Spread,
    Comma,
    Colon,
    Semicolon,
    Arrow,
    Question,
    Pipe,
    Bang,
    QuestionDot,
    QuestionQuestion,
    Increment,
    Decrement,
    Ampersand,
    BitwiseOr,
    BitwiseXor,
    BitwiseNot,
    LeftShift,
    RightShift,
    UnsignedRightShift,
    Exponent,
    AmpersandAssign,
    BitwiseOrAssign,
    BitwiseXorAssign,
    LeftShiftAssign,
    RightShiftAssign,
    UnsignedRightShiftAssign,
    ExponentAssign,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    TemplateStrStart,
    TemplateStrPart,
    TemplateStrEnd,
    TemplateInterpolationStart,
    TemplateInterpolationEnd,
    Eof,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub token_type: TokenType,
    pub value: String,
    pub position: Position,
}

impl Token {
    pub fn new(token_type: TokenType, value: String, position: Position) -> Self {
        Self {
            token_type,
            value,
            position,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinaryOperator {
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulo,
    Equal,
    NotEqual,
    LessThan,
    GreaterThan,
    LessEqual,
    GreaterEqual,
    And,
    Or,
    Range,
    NullCoalesce,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    LeftShift,
    RightShift,
    UnsignedRightShift,
    Exponent,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnaryOperator {
    Negate,
    Not,
    BitwiseNot,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AccessModifier {
    Public,
    Private,
    Protected,
}
